### ISSUE TITLE
[EN DateTimeV2] The datetimeV2 prebuilt entity does not recognize phrases such as the "the 20th"

### ISSUE THREAD

**Issue by tdurnford** [Microsoft/Recognizers-Text#1488] opened 2019-03-05 23:20 UTC
**Issue**
The datetimeV2 prebuilt entity does not recognize phrases such as the "the 20th", "the 2nd", or "the 1st" as valid dates. It does, however, recognize phrases like "the 20th of March."

**Expected Behavior**
The prebuilt entity should be able to detect phrases like "the 20th" and map them to the next viable date. For example, "the 20th" should resolve to 3-20-2019 since it is currently March 5th and the next "20th" would be March 20th.

**Comment by tellarin** [comment] 2019-03-11 03:39
For general usage this is by design as the form "the 20th" is not always a date.
Currently, enabling CalendarMode activates that behaviour, but it's not enabled by default.

**Comment by tellarin** [comment] 2019-03-11 03:40
I'll close this issue for now. Please feel free to comment here if there are other questions/suggestions related to the issue.

**Closed by tellarin** 2019-03-11 03:40 UTC
Labels: by design
