### ISSUE TITLE
[EN Number] Entities recognized incorrectly in input cases like "5k-20k"

### ISSUE THREAD

**Issue by perkins4j2** [microsoft/Recognizers-Text#2047] opened 2020-03-11 04:18 UTC
**Describe the bug**
Don't recognize 5k-20k

**To Reproduce**
1. code
```java
        Gson gson = new GsonBuilder().create();
        System.out.println("====A");
        String input = "5k-20k";
        System.out.println("input:" + input);

        System.out.println("====B");
        List<ModelResult> results = NumberRecognizer.recognizeNumber(input, Culture.Chinese);
        results.forEach(e -> {
            System.out.println(gson.toJson(e));
        });

        System.out.println("====C");
        results = NumberRecognizer.recognizeNumberRange(input, Culture.Chinese);
        results.forEach(e -> {
            System.out.println(gson.toJson(e));
        });
```

2.result
====A
input:5k-20k
====B
WARN: Look-behind groups with no maximum length not supported. Java version <= 8.
====C
{"text":"5k-20k","start":0,"end":6,"typeName":"numberrange","resolution":{}}

3.error
- recognizeNumber don't recognize
- recognizeNumberRange recognized,but `resolution is null`

**Expected behavior**
- recognizeNumber:5000,20000
- recognizeNumberRange:5000 - 20000

**Platform (please complete the following information):**
 - Platform:  Java
 - Environment: package & console
 - Version of package : master

**Comment by perkins4j2** [comment] 2020-03-11 04:25
debug info:
class:BaseNumberExtractor
method:extract(String source)
line:Match[] matches = RegExpUtility.getMatches(k, source);

k=((?<!(\d{1,10}\s{0,10})|[-－])[-－])?[\d１２３４５６７８９０]+\s*(K|k|M|G|T|B|b)
source=5k-20k

result:
5k
-20k

so modify code:
class:ChineseNumeric
filed:NegativeNumberTermsRegexNum
`public static final String NegativeNumberTermsRegexNum = "((?<!(\\d+\\s*)|[-－])[-－])";`
should be:
`public static final String NegativeNumberTermsRegexNum = "((?<!(\\d+\\s*)|[-－]))";`

test again :
I found the following entities (2):
{
  "text" : "5k",
  "start" : 0,
  "end" : 2,
  "typeName" : "number",
  "resolution" : {
    "value" : "5000"
  }
}
{
  "text" : "20k",
  "start" : 3,
  "end" : 6,
  "typeName" : "number",
  "resolution" : {
    "value" : "20000"
  }
}

**Comment by perkins4j2** [comment] 2020-03-11 04:50
another badcase:
====A
input:5k20k
====B
WARN: Look-behind groups with no maximum length not supported. Java version <= 8.
====C

debug info:
class:BaseNumberExtractor
method:extract(String source)
line:Match[] matches = RegExpUtility.getMatches(k, source);
result:
5
20
5k
20k

But maybe something is wrong, in BaseNumberExtractor.extract(String source)。
The filter is pass every matched result:
Optional<Match> srcMatches = matchSource.keySet().stream().filter(o -> o.index == finalStart && o.length == finalLength).findFirst();

**Comment by LionbridgeCSII** [comment] 2020-05-15 10:47
@tellarin, can this issue be closed? Or additional work is required?

**Comment by tellarin** [comment] 2020-05-15 11:14
@LionbridgeCSII this issue was originally reported in Java, but the issue is fixed only on .NET, so I don't think it can be closed. But Java is outside your scope.

**Comment by tellarin** [comment] 2020-05-21 07:11
Closing now as we've validated it works in Java too.

**Closed by tellarin** 2020-05-21 07:11 UTC
Labels: bug
