### ISSUE TITLE
[DotNet][DateTime] Try/Catch in code without any explicit action in DateTimeModel class

### ISSUE THREAD

**Issue by Bill7zz** [Microsoft/Recognizers-Text#1424] opened 2019-01-28 14:36 UTC
The Parse method has a try-catch statement without any explicit action.

        try
        {
            var extractResults = Extractor.Extract(query, refTime);

            foreach (var result in extractResults)
            {
                var parseResults = Parser.Parse(result, refTime);

                if (parseResults.Value is List<DateTimeParseResult> list)
                {
                    parsedDateTimes.AddRange(list);
                }
                else
                {
                    parsedDateTimes.Add(parseResults);
                }
            }

            // Filter out ambiguous cases. Naïve approach.
            parsedDateTimes = Parser.FilterResults(query, parsedDateTimes);
        }
        catch (Exception)
        {
            // Nothing to do. Exceptions in parse should not break users of recognizers.
            // No result.
        }

**Comment by tellarin** [comment] 2019-02-19 08:33
@Bill7zz this is by design, as a safeguard against an internal exception breaking recognition. It's better to return null than to kill the recognizers.
Ideally there should be an injection point for logging/telemetry that would capture such cases.
I'll close this issue for now as there are no near-term plan to implement one as different users of the recognizers have different compliance requirements for any collected data.

**Closed by tellarin** 2019-02-19 08:33 UTC
