### ISSUE TITLE
[EN DatetimeV2] Support cases like "2 upcoming years"

### ISSUE THREAD

**Issue by guom08** [Microsoft/Recognizers-Text#811] opened 2018-08-28 04:55 UTC
"upcoming" here could be "coming", "next", "previous", "last"
"years" here could be "decades", "months", "weeks", "days"

**Comment by tellarin** [comment] 2018-08-28 06:15
Duplicate of #720. Closing it here.

**Closed by tellarin** 2018-08-28 06:15 UTC
Labels: enhancement
