### ISSUE TITLE
[CN NumberRange] Cannot extract "100–200之间" in "找出100–200之间同时不包括 150的销售记录"

### ISSUE THREAD

**Issue by linzijia07** [Microsoft/Recognizers-Text#674] opened 2018-06-27 07:48 UTC
"找出100–200之间同时不包括 150的销售记录"

Only "100–200" is extracted and parsed into [100,200), while the groundtruth should be "100–200之间" as (100,200)

**Comment by aanandr** [comment] 2018-09-05 05:56
I dont understand the issue? Which area is this in? I think this is incorrectly assigned to me.

**Comment by tellarin** [comment] 2018-09-05 06:10
@aanandr it seems it was a mistake. Please disregard it. @Sothan is responsible for the issue.

**Comment by Sothan** [comment] 2018-09-13 03:00
"100–200之间" is the same as "between 100 and 200", and we parse them into [100, 200), so there is nothing to do in this issue.

**Comment by tellarin** [comment] 2018-10-18 05:46
@linzijia07 and @guom08, can you confirm this works as intended?

**Comment by tellarin** [comment] 2018-10-18 07:14
Confirmed to work now. Closing the issue.

**Closed by tellarin** 2018-10-18 07:14 UTC
Labels: bug
