### ISSUE TITLE
[EN Currency] Currency entity fails to tag Indian currency correctly

### ISSUE THREAD

**Issue by oriservetech** [Microsoft/Recognizers-Text#1031] opened 2018-12-05 04:48 UTC
**Is your feature request related to a problem? Please describe.**
I am using prebuilt currency entity in LUIS to detect Indian currencies mentioned in the user messages. The model is not well trained to extract currencies generally mentioned by users in different ways.

**Describe the solution you'd like**
Currently builtin currency entity can only extract Indian currency in the form of "5 Rs" but it is not able to detect "Rs 5", "1 Rupee", "5 Rupees", "1 Rupee 50 paise"

**Describe alternatives you've considered**
Haven't found any alternatives or ways to enhance a prebuilt entity

**Additional context**
Nothing

**Comment by tellarin** [comment] 2018-12-05 04:56
@oriservetech, thanks for reporting it. We've reproduced the issue here and fix should be available in the next release (1.1.5).

**Comment by oriservetech** [comment] 2018-12-05 05:19
Thank you @tellarin for quick action. Just to add to the way people mention Indian currency. Is there a way to also include the Indian rupee symbol and code (sign: ₹; code: INR) as well to extract currency. For reference - https://en.wikipedia.org/wiki/Indian_rupee

**Comment by tellarin** [comment] 2018-12-10 09:36
Extraction is fixed and the rupee symbol is also recognized now. The fix will be included in the next package and enter the release pipeline soon after that. 
It may take some time though, due to the end of the year holidays, for it to be released publicly.
Thanks.

**Closed by tellarin** 2018-12-10 09:36 UTC
Labels: bug
