### ISSUE TITLE
Extracted email containing period at the end

### ISSUE THREAD

**Issue by HanLiMS** [microsoft/Recognizers-Text#2190] opened 2020-06-24 01:45 UTC
Issue
Extracted email containing period at the end.

Sample Input
"Amy lives at One Microsoft Way, Redmond, WA 98052.  Her phone number is 1-733-999-1999 and she works at Microsoft (MSFT).  Her credit cards are: Visa 5111 1111 1111 1111, MasterCard 5500000000000006, American Express 3600 0000 0000 009, and Discover 6011-0000-0000-0004. Contact: randomtest@microsoft.com."

Response:
Detected "randomtest@microsoft.com." as "Email" -->  There should be no "." in the detected entity.

**Comment by tellarin** [comment] 2020-06-24 01:48
Duplicate of #2018.

**Closed by tellarin** 2020-06-24 01:48 UTC
Labels: duplicate
