### ISSUE TITLE
[EN DateTimeV2] "everyday" no longer picked up as a Set entity

### ISSUE THREAD

**Issue by jgreer013** [microsoft/Recognizers-Text#2715] opened 2021-09-14 22:36 UTC
**Describe the bug**
"everyday" is no longer picked up as a set entity. "every day" is correctly picked up.

**To Reproduce**
1. Get the DateTimeRecognizer with the options "DateTimeOptions.CalendarMode | DateTimeOptions.EnablePreview | DateTimeOptions.ExtendedTypes"
2. Get the DateTimeModel from the recognizer with Culture.English
3. Call model.Parse("Cortana, please schedule a meeting everyday, from 9 to 11 am.")

**Expected behavior**
Expect to resolve to a set entity

**Sample input/output**
query: "Cortana, please schedule a meeting everyday, from 9 to 11 am."

**Platform (please complete the following information):**
 - Platform: .NET
 - Environment: nuget package
 - 1.8.0

**Additional context**
Used to work through Luis

**Comment by aitelint** [comment] 2022-01-07 04:56
working on this

**Comment by aitelint** [comment] 2022-01-07 07:00
@tellarin, I cannot reproduce the issue

**Comment by tellarin** [comment] 2022-01-07 11:29
I've also validated this is supported across modes in .NET. Closing issue.

**Closed by tellarin** 2022-01-07 11:29 UTC
Labels: supported
