### ISSUE TITLE
[FR Email] dot at the end of an email address recognized as part of it

### ISSUE THREAD

**Issue by Oursse** [microsoft/Recognizers-Text#2208] opened 2020-07-10 07:26 UTC
**Describe the bug**
If there's a dot at the end of an email address, it's recognized as part of it

**To Reproduce**
Parse : "Mon email est ours@blanc.fr."
It returns :
```
{
  "Text": "ours@blanc.fr.",
  "Start": 14,
  "End": 27,
  "TypeName": "email",
  "Resolution": {
    "value": "ours@blanc.fr."
  }
}
```

**Expected behavior**
```
{
  "Text": "ours@blanc.fr",
  "Start": 14,
  "End": 26,
  "TypeName": "email",
  "Resolution": {
    "value": "ours@blanc.fr"
  }
}
```

**Platform**

- Platform: [.NET]
- Environment: [console app]
- Version of package [v1.4.0]

**Comment by tellarin** [comment] 2020-07-10 07:29
Dupe of #2190 (closed as dupe). Will be covered by the fix for #2018.

**Closed by tellarin** 2020-07-10 07:29 UTC
