### ISSUE TITLE
[Currency JP] Whitespaces ahead of Arabic numeral followed by the kanji numeral 万 ‘ten thousand’ fails to be recognized

### ISSUE THREAD

**Issue by nawanas** [microsoft/Recognizers-Text#2921] opened 2022-04-12 19:48 UTC
* これは 7万円です 'This is 70000 yen'--numeral/currency not recognized.  Removing white space (i.e.これは7万円です) leads to currency "70000 Japanese yen" being recognized/resolved

If the numeral before the currency unit is entirely arabic numerals, then it is recognized even with the preceding space:
• これは 700円です ‘this is 700 yen’ --700円 recognized and correctly resolved to 700 Japanese yen

Also, if the numeral is entirely kanji, then it is recognized even with the preceding space:
• これは 七万円です ‘this is 70000 yen’ --七万円 recognized and correctly resolved to 70000 Japanese yen

Even some combinations of arabic numerals and kanji behave properly with the preceding space:
• これは 7百円です ‘this is 700 yen’ --7百円 recognized and correctly resolved to 700 Japanese yen
• これは 7千円です ‘this is 7000 yen’ --7千円 recognized and correctly resolved to 7000 Japanese yen

It may just be limited to cases where the numeral is arabic numerals followed by some kanji numerals, perhaps limited to just 万 ‘ten thousand’.

**Comment by aitelint** [comment] 2022-04-14 03:51
@nawanas, I cannot reproduce this one. 
"これは 7万円です" returns "7万円" parsed as "70000 yen".
I tried other combinations (multiple spaces, tabs instead of spaces, spaces between arabic and kanji numerals, spaces between the number and the currency). In all cases "70000 yen" is extracted correctly.

**Comment by tellarin** [comment] 2022-05-16 11:22
Closing this is as it can't be reproduced and no extra info.
@aitelint please add the spec cases listed here in the next Japanese-related PR (if not already there) for documentation and to avoid future regressions. Thanks.

**Closed by tellarin** 2022-05-16 11:22 UTC
Labels: bug, Priority:P1
