### ISSUE TITLE
[DE DateTimeV2] The datetimeV2 prebuilt entity does not recognize the terms "montags", "dienstags",...,"sonntags".

### ISSUE THREAD

**Issue by rostam** [microsoft/Recognizers-Text#1791] opened 2019-08-08 07:54 UTC
**Describe the bug**
The term consists of a day of week and "s" is common in the German language to be used to specify a repetition. 

**To Reproduce**
1. Go to 'LUIS'
2. Type 'montags'

**Expected behavior**
There result should be a recurrent result. 

**Sample input/output**
If you enter "montags" as the input, the output will be:
```
"entities": [
    {
      "entity": "montags",
      "type": "builtin.datetimeV2.set",
      "startIndex": 0,
      "endIndex": 6,
      "resolution": {
        "values": [
          {
            "timex": "2019-08-05",
            "type": "set",
            "value": "not resolved"
          }
        ]
      }
    }
  ]
```

**Platform (please complete the following information):**
 - Platform: .NET
 - Environment: LUIS
 - Version of package: Last version

**Additional context**

**Comment by tellarin** [comment] 2019-08-08 08:32
@rostam this is the behaviour by design. These entities are are correctly recognized with the "Set" type, which means a recurring event. 
However, as there is no context to decide frequency or start/end of the recurrence, the assigned resolution is the canonical value "not resolved".
There are plans to extend the resolver library in \Microsoft.Recognizers.Text.DataTypes.TimexExpression to support receiving such entity output, along with the necessary context, to generate concrete well-defined resolutions. But this is likely not available in the short term.
I'll close this for now. Let us know if you have additional comments/questions.
Please check the behaviour of similar entities in English before opening issues. This can help clarify the expected behaviour of the recognizers.
But feel free to always open issues for discussion or to request new implementation!

**Closed by tellarin** 2019-08-08 08:32 UTC
Labels: supported
