### ISSUE TITLE
.NET RecognizeNumberRange return wrong closing character

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/Recognizers-Text#1908] opened 2019-10-21 08:52 UTC
**Describe the bug**
In .NET RecognizeNumberRange function return the correct value but the closing character is wrong.

Example : between 13 and 55  should return as (13,55) or [13,55] **but the value return like** **[13,55)**

**To Reproduce**
1. crete a object for NumberRecognizer and call the RecognizeNumberRange function 
2. function return the value with the wrong closing character

**Expected behavior**
Example : between 13 and 55  should return as **(13,55) or [13,55]**

**Sample input/output**
-

**Platform (please complete the following information):**
 - Platform:  .NET
 - Environment:Windows 10
-  Version of package [e.g. v1.0.8.1] - :

**Comment by tellarin** [comment] 2019-10-21 10:10
Hi @rvinothrajendran,
this is by design. All ranges in Recognizers text are inclusive of the start and exclusive of the end (unless marked in response as otherwise).
I'll close this for now, but fell free to comment further if you want to discuss alternatives or specific needs.

**Closed by tellarin** 2019-10-21 10:10 UTC
Labels: by design
