### ISSUE TITLE
[* DateTimeV2] Datetime return inclusive end time instead of exclusive for Months

### ISSUE THREAD

**Issue by a-hohaze** [Microsoft/Recognizers-Text#1507] opened 2019-03-25 11:31 UTC
**Is your feature request related to a problem? Please describe.**
Customer Request in LUIS

**Describe the solution you'd like**
when detecting DateTime for example "Dec 2018" instead of returning
`{
"timex": "2018-12",
"type": "daterange",
"start": "2018-12-01",
"end": "2019-01-01"
}`
return 
`{
"timex": "2018-12",
"type": "daterange",
"start": "2018-12-01",
"end": "2019-12-31"
}`

**Comment by tellarin** [comment] 2019-03-26 03:09
By default, all datetime ranges include their start point and exclude end point. In your example, Dec/2018 starts on 2018-12-01 (closed) and ends on 2019-01-01 (open), which means the last day is the previous day (2018-12-31). 
This behaviour is for consistency across all scenarios. Consumer applications can then decide how to treat intervals, as it's not always clear if they should be inclusive/exclusive and the module can't take this decisions (only applications have the necessary knowledge of their scenario).
The recognizers themselves have a feature flag to make all intervals inclusive, but this is not exposed on LUIS.
I'll close this issue as this is by design from the recognizers side and changes on the LUIS side are out of scope here, but feel free to continue the discussion if there are remaining questions.

**Closed by tellarin** 2019-03-26 03:09 UTC
Labels: by design
