### ISSUE TITLE
[EN DateTimeV2] "In half an hour" is not recognized correctly

### ISSUE THREAD

**Issue by MathieuDR** [microsoft/Recognizers-Text#2777] opened 2021-11-22 16:54 UTC
**Describe the bug**
When I give the parses "In half an hour" with a reference datetime, it will return a datetime with 5 hours added
![](https://i.imgur.com/jxUjma9.png)

**To Reproduce**
Try to recognize the query "In half an hour" with a reference date. The only resolution will be one with 5 hours added to the reference date

**Expected behavior**
Have 30 minutes added to the reference date

**Sample input/output**
```json
{
    "Query": "today in half an hour",
    "ExpectedDate": "2021-11-22 15:30:00",
    "ReferenceDate": "2021-11-22 15:00:00",
    "Output": [{
            "Text": "today",
            "Start": 0,
            "End": 4,
            "TypeName": "datetimeV2.date",
            "Resolution": {
                "values": [{
                        "timex": "2021-11-22",
                        "type": "date",
                        "value": "2021-11-22"
                    }
                ]
            }
        }, {
            "Text": "in half an hour",
            "Start": 6,
            "End": 20,
            "TypeName": "datetimeV2.datetime",
            "Resolution": {
                "values": [{
                        "timex": "2021-11-22T20:00:00",
                        "type": "datetime",
                        "value": "2021-11-22 20:00:00"
                    }
                ]
            }
        }
    ]
}
```
```json
{
    "Query": "in half an hour",
    "ExpectedDate": "2021-11-22 08:30:00",
    "ReferenceDate": "2021-11-22 08:00:00",
    "Output": [{
            "Text": "in half an hour",
            "Start": 0,
            "End": 14,
            "TypeName": "datetimeV2.datetime",
            "Resolution": {
                "values": [{
                        "timex": "2021-11-22T13:00:00",
                        "type": "datetime",
                        "value": "2021-11-22 13:00:00"
                    }
                ]
            }
        }
    ]
}
```
```json
{
    "Query": "in half an hour",
    "ExpectedDate": "2021-11-22 20:30:00",
    "ReferenceDate": "2021-11-22 20:00:00",
    "Output": [{
            "Text": "in half an hour",
            "Start": 0,
            "End": 14,
            "TypeName": "datetimeV2.datetime",
            "Resolution": {
                "values": [{
                        "timex": "2021-11-23T01:00:00",
                        "type": "datetime",
                        "value": "2021-11-23 01:00:00"
                    }
                ]
            }
        }
    ]
}

```

**Platform:**
 - Platform: .NET
 - Environment: nuget package, dotnet 6
 - Version of package 1.8.0

**Comment by aitelint** [comment] 2022-01-07 04:04
working on this

**Comment by aitelint** [comment] 2022-01-07 04:38
@tellarin, I cannot reproduce this issue, the pattern seems to be resolved correctly.

**Comment by tellarin** [comment] 2022-01-07 11:29
I've also validated this is supported across modes in .NET. Closing issue.

**Closed by tellarin** 2022-01-07 11:29 UTC
Labels: supported
