### ISSUE TITLE
[FR DateTimeV2] The date with the number below 12 is being recognized as month

### ISSUE THREAD

**Issue by fanidamj** [Microsoft/Recognizers-Text#346] opened 2018-02-13 17:48 UTC
The recognition is not working as expected. For query = 13/02/2018, the value recognized is 13th Feb 2018 but if the date specified in less than 12, eg, 09/02/2018, the value recognized is 2nd September 2018 instead of 9th Feb 2018.

**Comment by tellarin** [comment] 2018-02-23 05:17
Thanks for reporting this. We'll have a fix soon.

**Comment by nrobert** [comment] 2018-03-08 13:45
@tellarin , I had a look on this issue a while ago and figured that it may come from the order of the "DateExtractor", in particular those ones:

```
DateExtractor4: !nestedRegex
  def: \b{MonthNumRegex}\s*[/\\\-]\s*{DayRegex}\s*[/\\\-]\s*{DateYearRegex}
  references: [ MonthNumRegex, DayRegex, DateYearRegex ]
DateExtractor5: !nestedRegex
  def: \b{DayRegex}\s*[/\\\-]\s*{MonthNumRegex}\s*[/\\\-]\s*{DateYearRegex}
  references: [ DayRegex, MonthNumRegex, DateYearRegex ]
```

Those 2 regex will be matched if the day of the parsed date is 12 maximum.
And the 1st value, which is MM/DD format, will be then taken.

What is for you the best way to fix that kind of problem?
 - Invert Regex in `French-DateTime.yaml` file?
 - Invert declaration in `DateRegexList` in `FrenchDateExtractorConfiguration.cs`?

Thanks for your feedback.

**Comment by tellarin** [comment] 2018-04-13 03:47
@annesof We're working on a fix and hope it will be included on the next release.

**Comment by VincentGuigui** [comment] 2018-04-26 23:05
I guess you could remove the DateExtractor4 (month/day/year) as it's very uncommon to use this format in french

**Comment by nrobert** [comment] 2018-04-27 06:45
As the extractor quantity / name is a template shared between languages, I'm not sure it will work during generation.

But at least exchanging them would be ok

**Comment by tellarin** [comment] 2018-04-27 07:06
Hi folks, 

we have a more general fix in the pipeline and it will be in the next package release. Sorry for the delay.

**Comment by VincentGuigui** [comment] 2018-04-27 07:15
Thanks, 
do you have an ETA for the deployment to the eu.uis.ai endpoint ?

**Comment by tellarin** [comment] 2018-04-28 09:50
First piece of solution is merged (#505), which already solves the problem for French. A new package will be generated early next week. It should reach LUIS soon after that.
Thanks for your patience.

**Comment by VincentGuigui** [comment] 2018-05-15 17:48
It's fixed on the repo. Not deployed yet

For the input 04/08/2010 (august 4th 2010) we still have this :
```
"entities": [
    {
      "entity": "04/08/2010",
      "type": "builtin.datetimeV2.date",
      "startIndex": 0,
      "endIndex": 9,
      "resolution": {
        "values": [
          {
            "timex": "2010-04-08",
            "type": "date",
            "value": "2010-04-08"
          }
        ]
      }
    },
```
instead of 
```
"entities": [
    {
      "entity": "04/08/2010",
      "type": "builtin.datetimeV2.date",
      "startIndex": 0,
      "endIndex": 9,
      "resolution": {
        "values": [
          {
            "timex": "2010-08-04",
            "type": "date",
            "value": "2010-08-04"
          }
        ]
      }
    },
```

To be continued...

**Comment by tellarin** [comment] 2018-05-16 00:57
Thanks for catching this. We're looking at it right now.

**Comment by tellarin** [comment] 2018-05-16 01:01
I can't repro the issue in the repo. Or do you mean you still don't see it in LUIS?

**Comment by STayinloves** [comment] 2018-05-16 02:46
I have checked both .NET and JS, can't reproduce it.

**Comment by VincentGuigui** [comment] 2018-05-16 08:40
The repo is fine, but it's not deployed on Luis

**Comment by tellarin** [comment] 2018-05-18 10:00
It works for me in LUIS now. If something like this happens again, please mention where do you see the issue happen.
Thanks for reporting and tracking the issue.

**Closed by tellarin** 2018-05-18 10:00 UTC
Labels: bug
