### ISSUE TITLE
[EN DateTimeV2] "this week" is recognized as 8 days

### ISSUE THREAD

**Issue by KayMKM** [Microsoft/Recognizers-Text#1399] opened 2019-01-24 08:18 UTC
**Describe the bug**
The this week is recognized as 1/21-1/28, it should be 1/21-1/27

**To Reproduce**
use DateTimeRecognizer to recognize "this week"

**Expected behavior**
return start as "1/21" and end as "1/27"

**Sample input/output**
input: "next week"
output: 
start: "2019-01-21"
end: "2019-01-28"

**Platform (please complete the following information):**
 - Platform: .NET
 - Environment: nuget package
 - Version of package 1.1.4

**Additional context**

**Comment by tellarin** [comment] 2019-01-24 08:30
This is the behaviour by design. All intervals on the recognizers are inclusive of start and open at the end.
[start,end)

**Comment by KayMKM** [comment] 2019-01-24 11:23
> The week is tied to the ISO week number, and the start/end are calculated based on that definition.
> All intervals on the recognizers are by design inclusive of start and open at the end. E.g.: [start,end)

But if i say "1/21 to 1/27" it will return [start, end]. This is very confusing.

**Comment by guom08** [comment] 2019-01-25 03:54
> > The week is tied to the ISO week number, and the start/end are calculated based on that definition.
> > All intervals on the recognizers are by design inclusive of start and open at the end. E.g.: [start,end)
> 
> But if i say "1/21 to 1/27" it will return [start, end]. This is very confusing.

@KayMKM I believe there is no consistency. In our design, the date range is always open at the start and closed at the end. "1/21 to 1/27", we consider it as include "1/21" and exclude "1/27", which is 6 days in total. So the results are "start: 1/21" and "end: 1/27" with Timex "P6D". For "this week", we would return "start: 1/21" and "end: 1/28" with a 7 days span. So there is no inconsistency problem.

**Comment by tellarin** [comment] 2019-03-01 04:50
Closing as there seems to be correct according to @guom08.

**Closed by tellarin** 2019-03-01 04:50 UTC
Labels: analysis/openquestion, by design

**Comment by mrussek** [comment] 2021-09-25 00:31
@tellarin @guom08 Tell me if this should be another issue or not, but it seems very odd from my perspective to interpret "1/21 to 1/27" as excluding "1/27". Is there any more documentation on this decision?
