### ISSUE TITLE
Javascript AVA Test not running due to missing recognizers-text-number module

### ISSUE THREAD

**Issue by matthewshim-ms** [Microsoft/Recognizers-Text#335] opened 2018-02-09 17:51 UTC
![recognizers-issue-javascript-01](https://user-images.githubusercontent.com/26774878/36041795-89337404-0d7e-11e8-94a3-e6616115decc.png)

I've pulled the latest changes and run "npm run build" / used the build.cmd to initiate the lerna build. It seems that not all of the modules are being loaded correctly afterwards, as these are all of the contents of Javascript/node_modules/@microsoft after a fresh build 

![recognizers-issue-javascript-02](https://user-images.githubusercontent.com/26774878/36041805-902ad676-0d7e-11e8-9eef-5b9ace9a8701.png)

**Comment by wgx998877** [comment] 2018-02-11 09:04
Do you run "npm install" before npm run build ? @matthewshim-ms

**Comment by tellarin** [comment] 2018-02-12 05:24
@wgx998877, he's trying to build the GitHub project, not install on his machine.
Can you reproduce the problem? Is it maybe because of some left items from the previous build in his machine?

**Comment by matthewshim-ms** [comment] 2018-02-12 08:42
Thanks @tellarin , what was missing I think was not removing the compiled .js files from the /packages directory, go ahead and close

**Comment by tellarin** [comment] 2018-02-12 08:51
Closing :)

**Closed by tellarin** 2018-02-12 08:51 UTC
