### ISSUE TITLE
[DE DateTimeV2] The datetimeV2 prebuilt entity does not recognize the utterance "unter der Woche".

### ISSUE THREAD

**Issue by rostam** [microsoft/Recognizers-Text#1763] opened 2019-08-02 09:25 UTC
**Is your feature request related to a problem? Please describe.**
The utterance "unter der Woche" is a common utterance in the German language.

**Describe the solution you'd like**
This utterance should be mapped to the date range from Monday to Friday.

**Describe alternatives you've considered**

**Additional context**

**Comment by tellarin** [comment] 2019-08-07 00:44
Just to clarify, "unter der Woche" means roughly "during the work week", correct?
Do you think "während der Woche" should be recognized as the whole 7-day week? Or doesn't that make sense?

**Comment by rostam** [comment] 2019-08-07 07:23
Yes, you can consider both "unter der Woche" and "während der Woche" as 5-day week.

**Comment by tellarin** [comment] 2019-08-07 09:08
In other languages "during the week" treats week as the full 7-day week. Would it be OK to treat both in German as 7 too? My initial question was if "unter der Woche" required the special interpretation.
Consistency cross-languages is strongly desired to the extent possible.

**Comment by rostam** [comment] 2019-08-20 06:21
I checked both the current versions of code and LUIS and this issue is still not working. In both utterances, only the term "der Woche" is recognized.

**Comment by rostam** [comment] 2019-09-24 09:32
@tellarin The mentioned problems in this issue are not solved. I tested both the code and LUIS. Should we reopen this issue?

**Comment by tellarin** [comment] 2019-09-26 01:41
Thanks for following up. I'll run some tests on it soon.

**Comment by rudinas** [comment] 2019-11-25 10:45
Hello @tellarin , unfortunately this issue is not solved as reported, yet:
```
{
  "Text": "der woche",
  "Start": 6,
  "End": 14,
  "TypeName": "datetimeV2.daterange",
  "Resolution": {
    "values": [
      {
        "timex": "2019-W48",
        "type": "daterange",
        "start": "2019-11-25",
        "end": "2019-12-02"
      }
    ]
  }
}
```
Could you please reopen it?

**Comment by tellarin** [comment] 2019-12-04 02:37
@rudinas @rostam Sorry for the long delay to reply. It seems the issue is one of consistency with other languages.

As from 07/Aug:
> In other languages "during the week" treats week as the full 7-day week. Would it be OK to treat both in German as 7 days too? My initial question was if "unter der Woche" required the special interpretation.
> Consistency cross-languages is strongly desired to the extent possible.

Ideally we'd like to keep this consistency. Unless there is clearly no ambiguity in German that this form refers *only* to works days.

We can also add extra attributes to the response to highlight that it could also be interpreted as 5-day, if that helps.

What do you think?

**Comment by rostam** [comment] 2019-12-04 08:30
https://www.wortbedeutung.info/unter_der_Woche

There is no consistency between German and English for this term. "unter der Woche" unambiguously mean Mo-Fr.

In English, the nearest corresponding expression is "during the working week".

**Comment by tellarin** [comment] 2019-12-05 01:59
@rostam, is it exactly the same for "während der Woche"?

**Comment by rostam** [comment] 2019-12-09 09:04
@tellarin Sorry for late response. Not like "unter der Woche", it seems that the expression "während der Woche" is context specific and can mean both 7-day week or working week based on the context. So, we might consider this expression similar to the expression "during the week".

**Comment by tellarin** [comment] 2019-12-09 09:10
Thanks. We'll make this distinction.

**Comment by Ablesius** [comment] 2020-01-07 07:40
> How would you say "during the week" meaning the 7-day week in German? Or is there no common usage of such case?

"I will be able to tackle this during the week." -> By the end of the week, this could be done.
"Ich werde das diese Woche angehen" -> Roughly translation of the above. German just uses a temporal accusative to express the same thing.

**Comment by Ablesius** [comment] 2020-08-03 12:51
Hi,

is it possible to extend this feature request to also cover "werktags" (an adverbial expression to say "from Monday to Friday, inclusively")?

**Comment by Ablesius** [comment] 2020-08-03 13:20
If there's an existing PR, I'm open to contributing, too :)

**Comment by Ablesius** [comment] 2020-08-26 07:27
@tellarin any updates?

**Comment by tellarin** [comment] 2020-09-17 04:04
@Ablesius, this is finally merged and will be included in the next package update.

**Closed by tellarin** 2020-09-17 04:04 UTC
Labels: enhancement, lang-specific
