### ISSUE TITLE
[EN DateTimeV2] Emojis seem to cause boundary calculation issues

### ISSUE THREAD

**Issue by zoinkydoink** [microsoft/Recognizers-Text#2521] opened 2021-03-11 19:17 UTC
> LOTTERY IS LIVE! 🎰🎰 You can buy a ticket starting from now 🎟️ https://t.co/quIN6yhduT You only need to match 1 or more numbers in the right position to win a prize, very easy to win! 🎉🎉 First draw: March 11th, 2021 - 19:00 GMT+1 Instructions: https://t.co/v7iMTlsqe4 https://t.co/qC1c0K8Q90

vs 

> LOTTERY IS LIVE! You can buy a ticket starting from now  https://t.co/quIN6yhduT You only need to match 1 or more numbers in the right position to win a prize, very easy to win! First draw: March 11th, 2021 - 19:00 GMT+1 Instructions: https://t.co/v7iMTlsqe4 https://t.co/qC1c0K8Q90

Will produce different results if you remove emojis before passing them into the extractor.
Specifically it messes up the GMT+1 and does not take the +1 into consideration

**Comment by tellarin** [comment] 2021-03-16 08:57
Interesting bug caused by the Unicode variation selector (\uFE0F) in 🎟️. Fix on the way.
Thanks for the report.

**Comment by tellarin** [comment] 2021-04-14 09:30
The fix is in the repo and it will be part of release v1.6.1 coming soon.

**Closed by tellarin** 2021-04-14 09:30 UTC
Labels: bug
