### ISSUE TITLE
[ZH Number]"千分之一"、"仟分之贰"、"万分之三"、"萬分之肆" can't be recognized as number or percentage number

### ISSUE THREAD

**Issue by SoaringTiger** [microsoft/Recognizers-Text#2267] opened 2020-09-08 07:16 UTC
**Describe the bug**
"千分之一"、"仟分之贰"、"万分之三"、"萬分之肆" can't be recognized as number or percentage number

**Expected behavior**
"千分之一" and "一千分之一" mean 0.001  (1‰) ， but "千分之一" can't be recognized as number or percentage number.
Similarly，
"仟分之贰" and "壹仟分之贰" mean 0.002  (2‰) 
"万分之三" and "一万分之三" mean 0.0003  (3‱）
"萬分之肆" and "壹萬分之肆" mean 0.0004  (4‱）
"百万分之五" and "一百万分之五" mean 5E-06 (0.5‱）
"千万分之六" and "一千万分之六" mean 6E-07 (0.06‱）
"万万分之七" and "一万万分之七" mean 7E-08 (0.007‱）
etc.

**Platform (please complete the following information):**
 - Platform: [.NET]
 - Version of package [v1.4.1]

**Comment by tellarin** [comment] 2020-09-15 03:09
Closing it as duplicate of #2257 and being addressed in PR #2269.

**Closed by tellarin** 2020-09-15 03:09 UTC
Labels: duplicate
