### ISSUE TITLE
[*|EN Currency] ALL is picked up as a currency

### ISSUE THREAD

**Issue by nawanas** [microsoft/Recognizers-Text#2858] opened 2022-02-09 16:14 UTC
**Describe the bug**
using the expression ALL followed by a number (ALL 5 of us) detects the expression as a currency (Albanian Lek). This is not part of the patterns that are associated with the Albanian LEK, but probably captured elsewhere.

**Additional context**
Please add a spec to capture that this should't be detected

 {
    "Input": "All 70 of us",
    "Results": [
      {
        "Text": "70",
        "TypeName": "number",
        "Resolution": {
          "subtype": "integer",
          "value": "70",
          },
        "Start": 4,
        "End": 6
      }
    ]
  }

**Comment by tellarin** [comment] 2022-03-04 03:20
Moving to P1 as requested by users. @aitelint, can you add the P1 issues to your list as the KO/JA work comes along?

**Comment by assafi** [comment] 2022-03-07 05:58
@tellarin Looks like this happens because we include all of the currencies ISO values as valid prefixes, including the Albanian LEK (ALL). This seems a bit odd to me. I would expect we would add the ISO to the suffix list, but not the prefix (i.e. "10 EUR" makes sense, but not "EUR 10"). 
Do you know if this is by-design? Should we add an exclusion list to this rule or change it?

**Comment by tellarin** [comment] 2022-03-07 06:14
@assafi This is by design. "EUR 10" is a valid and common form. There are other mechanisms to handle ambiguous cases as in this issue that can be used.

**Comment by kayousef** [comment] 2022-03-07 10:22
@tellarin @assafi Can we rely on case sensitive matching in this case? Currency codes should always be ALL CAPS.
So we only match a currency code if we match "ALL", not "All".

Thoughts?

**Comment by tellarin** [comment] 2022-03-07 10:31
That's now how the engine works. Do you want to contribute a fix yourself? We're waiting for the vendor to have bandwidth to close this. Matthew is the contact person (@nawanas, do you remember Matthew's GitHub username?).

**Comment by nawanas** [comment] 2022-03-07 11:01
I don't remember it, i recall pinging him on this for a few times will do that again

**Closed** 2022-03-25 09:47 UTC
Labels: bug, Priority:P1
