### ISSUE TITLE
[EN DateTimeV2] Parser resolves in the past by default

### ISSUE THREAD

**Issue by RomainWilbert** [Microsoft/Recognizers-Text#495] opened 2018-04-26 13:13 UTC
"11/24" => "24/11/2017"
"tuesday" (when today is thursday 11/26) => "24/04/2018 00:00:00 +02:00"

Without any explicit chronology data (last, next), parser should assume that the date is in the future.

Or maybe there could be a DateTimeOption to set chronology preference ?

**Comment by tellarin** [comment] 2018-04-27 11:54
Hi @RomainWilbert,

where do you see this behaviour? By design the recognizer provides two resolutions (past and future) for such ambiguous cases, so the module consumer can choose the appropriate value to use.

Output follows a format like:
{
  "Text": "11/24",
  "Start": 0,
  "End": 4,
  "TypeName": "datetimeV2.date",
  "Resolution": {
    "values": [
      {
        "timex": "XXXX-11-24",
        "type": "date",
        "value": "2017-11-24"
      },
      {
        "timex": "XXXX-11-24",
        "type": "date",
        "value": "2018-11-24"
      }
    ]
  }
}

**Comment by RomainWilbert** [comment] 2018-04-27 11:58
My bad, I missed that as I read the first (and i thought only) resolution.
Can I assume that the first resolution is the one in the past, and so the second in the future ?

**Comment by tellarin** [comment] 2018-04-27 11:58
Yes, that's typically the case. 

I'll close this issue then, ok?

**Closed by tellarin** 2018-04-27 11:58 UTC
