### ISSUE TITLE
Utterance with numbers like 2/3 as second entity does not work correctly with prebuilt entity - number

### ISSUE THREAD

**Issue by asishsinha** [microsoft/Recognizers-Text#2038] opened 2020-02-14 15:40 UTC
**Describe the bug**
If numbers such as 2/3 are used as part of utterance, it does not work correctly for number.

**To Reproduce**
1. Go to LUIS portal, add prebuilt entity - number, train and test.
2. Type '30 1/2'
4. See issue
![image](https://user-images.githubusercontent.com/10179672/74544862-db730800-4f6d-11ea-9293-10313c41d042.png)

**Expected behavior**
For the input "30 1/2"
Output: 
30 - number
1/2 - number

**Sample input/output**
Input: "30 1/2"
Output: 
"30 1/2" - number

**Platform (please complete the following information):**
 - LUIS, portal

**Additional context**

The below works correctly:
![image](https://user-images.githubusercontent.com/10179672/74545030-3147b000-4f6e-11ea-9f37-d3576932d92b.png)

**Comment by tellarin** [comment] 2020-02-26 00:19
This behaviour is by design. "30 1/2" is the regular notation for 30 + 1/2 = 30.5, so it's only one entity.
The second case is different, as there is no notation that takes a fraction first. So the output has two separate entities.
I'll close this issue. Feel free to add comments for discussion and we can create another issue if necessary).

**Closed by tellarin** 2020-02-26 00:19 UTC

**Comment by sunnysharma03** [comment] 2020-02-26 14:47
Hi @tellarin the behavior changes if the input is: 3/1 2/3
It won't recognized as number entity
