### ISSUE TITLE
[DateTime2 .NET] Polygon! 20th April, 5 PM IST not picking right timezone

### ISSUE THREAD

**Issue by zoinkydoink** [microsoft/Recognizers-Text#2562] opened 2021-04-20 04:22 UTC
`Polygon! 20th April, 5 PM IST`
Produces the right date and time, but the timezone is picked as `UTC\u002BXX:XX` with a `UtcOfsetMinutes `of `-10000`

**Comment by zoinkydoink** [comment] 2021-04-20 04:27
should i be creating an issue for every one of these i find or create one issue and put them all in that?

**Comment by tellarin** [comment] 2021-04-20 05:01
@zoinkydoink you can group them into more general issues, if you can.
But this one is not an error. Ambiguous timezones are all resolved to XX:XX and IST is one of them. There is an item in the backlog to return all possibilities, but that will take some time to be released.
As this one behaves correctly "by design", I'll close the issue, ok? But feel free to reply here to continue the discussion and we can create other issues as relevant.

**Closed by tellarin** 2021-04-20 05:01 UTC
Labels: by design, enhancement

**Comment by zoinkydoink** [comment] 2021-04-20 16:16
following also results in timezone not being resolved
`April 20, 3PM BST / 4PM CET`

**Comment by zoinkydoink** [comment] 2021-04-21 19:16
following is not picking up the right time in the datetime field, however it is picking up a timex field with the right time
I assume it should include the time with the date that is parsed instead of separating them into multiple resolutions
 `3am (UTC) on April 22`

**Comment by zoinkydoink** [comment] 2021-04-22 01:32
` April 22, 5am UTC ` does not result in timezone

**Comment by zoinkydoink** [comment] 2021-04-23 01:38
following does not give a timezone result `The AMA will kick off 27 April, 10am (GMT-3)`

**Comment by zoinkydoink** [comment] 2021-04-24 05:22
no timezone resolution for `April 25, 2021, 10:00 (GMT+8)`
